services:
  app:
    build: .
    container_name: app
    working_dir: /var/www
    volumes:
      - ./ahago-backend:/var/www
      - ./php.ini:/usr/local/etc/php/php.ini
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: nginx_server
    ports:
      - "8300:80"
    volumes:
      - ./ahago-backend:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ahago
      MYSQL_USER: ahago
      MYSQL_PASSWORD: ahago
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ahago
      MINIO_ROOT_PASSWORD: ahago123
      MINIO_PROMETHEUS_AUTH_TYPE: public
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - laravel

volumes:
  db_data:
  minio-data:

networks:
  laravel:
    driver: bridge
